import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-excelinfo-form',
  templateUrl: './excelinfo-form.component.html',
  styleUrls: ['./excelinfo-form.component.css']
})
export class ExcelinfoFormComponent implements OnInit {

    //excelinfo table properties
    _loading: boolean;

    excelInfoDataSource = [
        {Chr: 'chr1', Start: '976554', End: '976554', Ref: 'C', Alt: 'G', Func_refGene: 'exonic', Gene_refGene: 'AGRN', GeneDetail_refGene: '.', ExonicFunc_refGene: 'synonymous SNV', AAChange_refGene: 'AGRN:NM_198576:exon5:c.C729G:p.G243G', Xref_refGene: 'Myasthenic syndrome, congenital, 8, with pre- and postsynaptic defects, Autosomal recessive', cytoBand: '1p36.33', genomicSuperDups: '.', esp6500siv2_all: '.', _1000g2014oct_all: '0.0255591', _1000g2014oct_afr: '0.0651', _1000g2014oct_eas: '0.0268', _1000g2014oct_eur: '0.003', Local_freq: "'6/180", ExAC_EAS: "'2/102", ExAC_ALL: "'163/68250", GnomAD_EAS: "'21/1044", GnomAD_ALL: "'284/50964", GnomAD_Hom: "'1", avsnp147: 'rs191270495', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '0.5', AZ: '424.77', BA: '33', BB: 'chr1', BC: '976554', BD: '.', BE: 'C', BF: 'G', BG: '424.77', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr1', Start: '977330', End: '977330', Ref: 'T', Alt: 'C', Func_refGene: 'intronic', Gene_refGene: 'AGRN', GeneDetail_refGene: 'AGRN:NM_198576.3:intron6:c.1178-6T>C', ExonicFunc_refGene: '.', AAChange_refGene: '.', Xref_refGene: 'Myasthenic syndrome, congenital, 8, with pre- and postsynaptic defects, Autosomal recessive', cytoBand: '1p36.33', genomicSuperDups: '.', esp6500siv2_all: '0.8526', _1000g2014oct_all: '0.885184', _1000g2014oct_afr: '0.6899', _1000g2014oct_eas: '0.999', _1000g2014oct_eur: '0.9245', Local_freq: "'180/180", ExAC_EAS: "'8480/8482", ExAC_ALL: "'110465/120770", GnomAD_EAS: "'17108/17112", GnomAD_ALL: "'222664/241110", GnomAD_Hom: "'103312", avsnp147: 'rs2799066', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '1', AZ: '5298.77', BA: '180', BB: 'chr1', BC: '977330', BD: '.', BE: 'T', BF: 'C', BG: '5298.77', BH: 'PASS', BI: 'AC=2;AF=1.00;AN=2;DP=180;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;QD=29.44;SOR=1.080'},
        {Chr: 'chr1', Start: '979690', End: '979690', Ref: 'G', Alt: 'A', Func_refGene: 'intronic', Gene_refGene: 'AGRN', GeneDetail_refGene: 'AGRN:NM_198576.3:intron6:c.1178-6T>C', ExonicFunc_refGene: '.', AAChange_refGene: '.', Xref_refGene: 'Myasthenic syndrome, congenital, 8, with pre- and postsynaptic defects, Autosomal recessive', cytoBand: '1p36.33', genomicSuperDups: '.', esp6500siv2_all: '0.0215', _1000g2014oct_all: '0.0299521', _1000g2014oct_afr: '0.0825', _1000g2014oct_eas: '0.0268', _1000g2014oct_eur: '0.003', Local_freq: "'6/180", ExAC_EAS: "'265/8518", ExAC_ALL: "'1529/121158", GnomAD_EAS: "'465/17190", GnomAD_ALL: "'2721/244692", GnomAD_Hom: "'43", avsnp147: 'rs115413462', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '0.5', AZ: '1550.77', BA: '140', BB: 'chr1', BC: '979690', BD: '.', BE: 'G', BF: 'A', BG: '1550.77', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=-3.972e+00;ClippingRankSum=0.00;DP=140;ExcessHet=3.0103;FS=17.607;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=11.08;ReadPosRankSum=0.680;SOR=0.957'},
        {Chr: 'chr2', Start: '1437410', End: '1437410', Ref: 'C', Alt: 'T', Func_refGene: 'intronic', Gene_refGene: 'TPO', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr2', Start: '1457465', End: '1457465', Ref: 'G', Alt: 'T', Func_refGene: 'splicing', Gene_refGene: 'TPO', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr2', Start: '1459922', End: '1459922', Ref: 'C', Alt: 'T', Func_refGene: 'exonic', Gene_refGene: 'TPO', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr3', Start: '3194107', End: '3194107', Ref: '-', Alt: 'A', Func_refGene: 'intronic', Gene_refGene: 'CRBN', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr3', Start: '3194325', End: '3194325', Ref: 'T', Alt: 'C', Func_refGene: 'intronic', Gene_refGene: 'CRBN', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr3', Start: '3197871', End: '3197871', Ref: 'T', Alt: 'C', Func_refGene: 'intronic', Gene_refGene: 'CRBN', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr4', Start: '648643', End: '648643', Ref: 'G', Alt: 'A', Func_refGene: 'exonic', Gene_refGene: 'PDE6B', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr4', Start: '663908', End: '663908', Ref: 'A', Alt: 'G', Func_refGene: 'exonic', Gene_refGene: 'PDE6B', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr4', Start: '980971', End: '980971', Ref: 'T', Alt: 'G', Func_refGene: 'exonic', Gene_refGene: 'IDUA', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
        {Chr: 'chr4', Start: '985727', End: '985727', Ref: 'A', Alt: 'G', Func_refGene: 'intronic', Gene_refGene: 'IDUA;SLC26A1', GeneDetail_refGene: '', ExonicFunc_refGene: '', AAChange_refGene: '', Xref_refGene: '', cytoBand: '', genomicSuperDups: '', esp6500siv2_all: '', _1000g2014oct_all: '', _1000g2014oct_afr: '', _1000g2014oct_eas: '', _1000g2014oct_eur: '', Local_freq: '', ExAC_EAS: '', ExAC_ALL: '', GnomAD_EAS: '', GnomAD_ALL: '', GnomAD_Hom: '', avsnp147: '', SIFT_score: '', SIFT_pred: '', Polyphen2_HDIV_score: '', Polyphen2_HDIV_pred: '', Polyphen2_HVAR_score: '', Polyphen2_HVAR_pred: '', LRT_score: '', LRT_pred: '', MutationTaster_score: '', MutationTaster_pred: '', MutationAssessor_pred: '', FATHMM_score: '', FATHMM_pred: '', RadialSVM_score: '', RadialSVM_pred: '', LR_score: '', LR_pred: '', VEST3_score: '', CADD_raw: '', CADD_phred: '', GERP_RS: '', phyloP46way_placental: '', phyloP100way_vertebrate: '', SiPhy_29way_logOdds: '.', Otherinfo: '', AZ: '', BA: '', BB: '', BC: '', BD: '', BE: '', BF: '', BG: '', BH: 'PASS', BI: 'AC=1;AF=0.500;AN=2;BaseQRankSum=2.22;ClippingRankSum=0.00;DP=33;ExcessHet=3.0103;FS=1.624;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=12.87;ReadPosRankSum=0.222;SOR=1.125'},
    ];

    //excelTableHeadArray = ['Chr','Start','Ref','Alt','Func_refGene','Gene_refGene','GeneDetail_refGene','ExonicFunc_refGene','AAChange_refGene','Xref_refGene','cytoBand','genomicSuperDups','esp6500siv2_all','_1000g2014oct_all','_1000g2014oct_afr','_1000g2014oct_eas','_1000g2014oct_eur','Local_freq','ExAC_EAS','ExAC_ALL','GnomAD_EAS','GnomAD_ALL','GnomAD_Hom','avsnp147','SIFT_score','SIFT_pred','Polyphen2_HDIV_score','Polyphen2_HDIV_pred','Polyphen2_HVAR_score','Polyphen2_HVAR_pred','LRT_score','LRT_pred','MutationTaster_score','MutationTaster_pred','MutationAssessor_score','MutationAssessor_pred','FATHMM_score','FATHMM_pred','RadialSVM_score','RadialSVM_pred','LR_score','LR_pred','VEST3_score','CADD_raw','CADD_phred','GERP_RS','phyloP46way_placental','phyloP100way_vertebrate','SiPhy_29way_logOdds','Otherinfo','AZ','BA','BB','BC','BD','BE','BF','BG','BH','BI'];
    excelTableHeadArray = ['Chr','Start','Ref','Alt','Func_refGene','Gene_refGene'];

    copyExcelInfoDataSource = [...this.excelInfoDataSource];
    sortName: string = null;
    sortValue: string = null;
    //切换nz-table-sort tab状态
    sortMap = {
        Chr: null,
        Start: null,
        Func_refGene: null,
        Gene_refGene: null
    }

    constructor() { }

    ngOnInit() {

    }

    //excelinfo table functions
    sort(theadItem, value) {
        console.log("sortName:" +theadItem + " value: " + value);
        this.sortName = theadItem;
        this.sortValue = value;
        Object.keys(this.sortMap).forEach(key => {
            if(key !== theadItem) {
                this.sortMap[key] = null;
            } else {
                this.sortMap[key] = value;
            }
        })
        this.showSortedItem();
    }

    showSortedItem() {
        this._loading = true;
        this.excelInfoDataSource = [ ...this.excelInfoDataSource.sort((a,b) => {
            if(a[this.sortName] > b[this.sortName]) {
                return (this.sortValue === 'ascend') ? 1 : -1;
            }else if(a[this.sortName] < b[this.sortName]) {
                return (this.sortName === 'ascend') ? -1 :1;
            } else {
                return 0;
            }
        })];
        this._loading = false;
    }

}
